language: erlang
otp_release:
    - 18.2.1
    - 17.5

sudo: false
addons:
  apt:
    packages:
    - python-virtualenv

cache:
  directories:
    - _build/dialyzer
    - _build/venv
before_cache:
    - rm -rf _build/dialyzer/lib

install:
    - make setup
script:
    - make
after_success:
    - make coveralls
