language: erlang
otp_release:
    - 18.2.1
    - 17.5
addons:
  apt:
    packages:
    - python-virtualenv

cache:
  directories:
    - _build/dialyzer
    - _build/venv
before_cache:
    - rm -f _build/dialyzer/lib

before_script: make setup
script: make
